name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  SVDTOOLS: svdtools

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Use the latest ${{ matrix.rust }} rustc
      #   run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Add Cortex-M4F target
        run: rustup target add thumbv7em-none-eabihf

      - uses: actions-rs/cargo@v1
        with:
          command: check

      # - name: Run tests
      #   run: cargo test --verbose
