name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  SVDTOOLS: svdtools

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add Cortex-M4F target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf
          components: clippy

      - name: Run Check
        run: cargo check
        continue-on-error: true

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
        continue-on-error: true

      # - name: Test
      #   run: |
      #     cargo test --verbose

      # - name: Build
      #   run: |
      #     cargo build --verbose

      # - name: Install required cargo
      #   run: cargo install clippy-sarif sarif-fmt

      # - name: Run rust-clippy
      #   run:
      #     cargo clippy
      #     --all-features
      #     --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      #   continue-on-error: true

      # - name: Upload analysis results to GitHub
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: rust-clippy-results.sarif
      #     wait-for-processing: true